# Assignment 3 

## Questions 1:
### Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [30]:
import numpy as np 
print(np.arange(2,50,3)) 

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


## Questions 2:
### Accept two lists of 5 elements each from the user.
### Convert them to numpy arrays. Concatenate these arrays and print it. 
### Also sort these arrays and print it.

In [31]:
list_1 = []
list_2 = []
for i in range(5):
    num = int(input('enter 1st list numbers ::'))
    list_1.append(num)
for i in range(5):    
    num2 = int(input('enter 2nd list numbers ::'))
    list_2.append(num2)
print(list_1)
print(list_2)
array_1 = np.array(list_1)
array_2 = np.array(list_2)

concatenated_array = np.concatenate((array_1, array_2), axis=0)
print("concatenated array is :", concatenated_array)
concatenated_array.sort()
print("sorted array is :", concatenated_array)

enter 1st list numbers ::4
enter 1st list numbers ::5
enter 1st list numbers ::6
enter 1st list numbers ::7
enter 1st list numbers ::8
enter 2nd list numbers ::11
enter 2nd list numbers ::5
enter 2nd list numbers ::45
enter 2nd list numbers ::78
enter 2nd list numbers ::45
[4, 5, 6, 7, 8]
[11, 5, 45, 78, 45]
concatenated array is : [ 4  5  6  7  8 11  5 45 78 45]
sorted array is : [ 4  5  5  6  7  8 11 45 45 78]


## Questions 3:
### Write a code snippet to find the dimensions of a ndarray and its size.


In [32]:
arr2D = np.array([[1,2,3,4], [5, 6, 7, 8], [45,85,99,199]])
print('Array as follows::')
print(arr2D)
number_of_rows = np.size(arr2D, 0)
number_of_coloumns = np.size(arr2D, 1)
print('Number of Rows :', number_of_rows)
print('Number of Columns :', number_of_coloumns)


Array as follows::
[[  1   2   3   4]
 [  5   6   7   8]
 [ 45  85  99 199]]
Number of Rows : 3
Number of Columns : 4


## Questions 4:
### How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
### Hint: np.newaxis, np.expand_dims

In [33]:
oneDarr = np.array([45, 89, 16, 75, 63, 75, 45, 15, 13, 450])
print('1D array is as Follows:')
print(oneDarr)
arr_2d = np.reshape(oneDarr, (2, 5))
print("2D Array is as foloows ")
print(arr_2d)

1D array is as Follows:
[ 45  89  16  75  63  75  45  15  13 450]
2D Array is as foloows 
[[ 45  89  16  75  63]
 [ 75  45  15  13 450]]


## Questions 5:
### Consider two square numpy arrays. Stack them vertically and horizontally.
### Hint: Use vstack(), hstack()

In [34]:
a = np.array([[10, 20, 30, 40], 
              [33, 43, 53, 63],
             [31, 41, 51, 61]]) 
  
b = np.array([[52, 62, 72, 82], 
              [77, 88, 99, 66],
             [59, 68, 76, 86]]) 
print("Vertical stacking:\n", np.vstack((a, b))) 
print('\n')
print("Horizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[10 20 30 40]
 [33 43 53 63]
 [31 41 51 61]
 [52 62 72 82]
 [77 88 99 66]
 [59 68 76 86]]


Horizontal stacking:
 [[10 20 30 40 52 62 72 82]
 [33 43 53 63 77 88 99 66]
 [31 41 51 61 59 68 76 86]]


## Questions 6:
### How to get unique items and counts of unique items?

In [35]:
def unique(list_1): 
    a = np.array(list_1) 
    print(np.unique(a)) 
      
list_1 = [11, 22, 33, 44, 55, 66, 77, 88, 99] 
print("The unique are") 
unique(list_1) 
set_1 = set(list_1) 
print("No of unique items in the list are:", len(set_1))

The unique are
[11 22 33 44 55 66 77 88 99]
No of unique items in the list are: 9
